/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Canonical schema for agent operational manifests.
 */
export interface AgentRecord {
  /**
   * Unique identifier for the agent, linking to an ActorRecord.
   */
  id: string;
  status?: "active" | "archived";
  guild: "design" | "intelligence" | "strategy" | "operations" | "quality";
  triggers?: {
    type: "manual" | "webhook" | "scheduled";
    [k: string]: unknown;
  }[];
  knowledge_dependencies?: string[];
  prompt_engine_requirements?: {
    roles?: string[];
    skills?: string[];
    [k: string]: unknown;
  };
  engine:
    | {
        type: "local";
        runtime?: string;
        entrypoint?: string;
        function?: string;
        [k: string]: unknown;
      }
    | {
        type: "api";
        url?: string;
        method?: "POST" | "GET";
        auth?: {
          [k: string]: unknown;
        };
        [k: string]: unknown;
      }
    | {
        type: "mcp";
        url?: string;
        auth?: {
          [k: string]: unknown;
        };
        [k: string]: unknown;
      };
  [k: string]: unknown;
}
