/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Canonical schema for changelog records - Enterprise Grade System Historian
 */
export interface ChangelogRecord {
  /**
   * Unique identifier for the changelog entry
   */
  id: string;
  /**
   * Type of the primary entity that changed
   */
  entityType: "task" | "cycle" | "agent" | "system" | "configuration";
  /**
   * ID of the primary entity that changed
   */
  entityId: string;
  /**
   * The nature of the change
   */
  changeType: "creation" | "completion" | "update" | "deletion" | "hotfix";
  /**
   * Executive title of the change
   */
  title: string;
  /**
   * Detailed description of the change and its impact
   */
  description: string;
  /**
   * Unix timestamp in seconds when the change occurred
   */
  timestamp: number;
  /**
   * How the change was initiated
   */
  trigger: "manual" | "automated" | "emergency";
  /**
   * Actor or agent ID that initiated the change
   */
  triggeredBy: string;
  /**
   * Why the change was made
   */
  reason: string;
  /**
   * Risk level of the change
   */
  riskLevel: "low" | "medium" | "high" | "critical";
  /**
   * IDs of systems impacted by this change
   */
  affectedSystems?: string[];
  /**
   * Number of users impacted by this change
   */
  usersAffected?: number;
  /**
   * Downtime in seconds caused by this change
   */
  downtime?: number;
  /**
   * List of main files that were created or modified
   */
  files?: string[];
  /**
   * List of git commit hashes related to this change
   */
  commits?: string[];
  /**
   * Step-by-step instructions to rollback this change
   */
  rollbackInstructions?: string;
  /**
   * Cross-references to other GitGovernance records
   */
  references?: {
    /**
     * IDs of related TaskRecords
     */
    tasks?: string[];
    /**
     * IDs of related CycleRecords
     */
    cycles?: string[];
    /**
     * IDs of related ExecutionRecords
     */
    executions?: string[];
    /**
     * IDs of related ChangelogRecords
     */
    changelogs?: string[];
  };
}
