#!/bin/bash
# GitGovernance CLI - Local Portable Installer
# Creates a portable wrapper that works from any directory

set -e

# Configuration
INSTALL_DIR="$HOME/.local/bin"
WRAPPER_NAME="gitgov"
CLI_SOURCE_PATH="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

echo "🚀 Installing GitGovernance CLI (Local Portable)..."

# Create install directory if it doesn't exist
mkdir -p "$INSTALL_DIR"

# Create portable wrapper
cat > "$INSTALL_DIR/$WRAPPER_NAME" << 'EOF'
#!/bin/bash
# GitGovernance CLI - Portable Local Wrapper (INFALIBLE)
# Generated by install-local-portable.sh

# SAFETY CHECK: Detect if we're inside a GitGovernance project
CURRENT_DIR="$(pwd)"
SEARCH_DIR="$CURRENT_DIR"

# Search upward for existing .gitgov (this means we're inside a GitGovernance project)
INSIDE_GITGOV_PROJECT=""
while [ "$SEARCH_DIR" != "/" ]; do
    if [ -d "$SEARCH_DIR/.gitgov" ]; then
        INSIDE_GITGOV_PROJECT="$SEARCH_DIR"
        break
    fi
    SEARCH_DIR="$(dirname "$SEARCH_DIR")"
done

# If inside GitGovernance project, only allow read commands, block init
if [ -n "$INSIDE_GITGOV_PROJECT" ]; then
    if [[ "$1" == "init" ]]; then
        echo "❌ ERROR: Cannot init inside existing GitGovernance project at: $INSIDE_GITGOV_PROJECT"
        echo ""
        echo "🎯 Use the correct command for your location:"
        echo "   • From /packages/cli/: pnpm dev init"
        echo "   • From project root: gitgov init"
        echo ""
        echo "💡 gitgov init is ONLY for external directories"
        echo "   Example: cd /tmp/demo && git init && gitgov init"
        exit 1
    fi
    
    # For read commands (status, dashboard), use the existing .gitgov
    unset GITGOV_ORIGINAL_DIR  # Let it find the existing .gitgov
fi

# SAFETY CHECK: Ensure we're in a git repository for init command
if [[ "$1" == "init" ]]; then
    if [ ! -d ".git" ]; then
        echo "❌ ERROR: Not a Git repository"
        echo "💡 Run 'git init' first, then 'gitgov init'"
        exit 1
    fi
fi

# Store original directory where user executed command
export GITGOV_ORIGINAL_DIR="$(pwd)"

# Execute CLI from source with proper context
cd "CLI_SOURCE_PATH_PLACEHOLDER"
npx tsx src/index.ts "$@"
EOF

# Fix the CLI_SOURCE_PATH in the generated script
sed -i '' "s|CLI_SOURCE_PATH_PLACEHOLDER|$CLI_SOURCE_PATH|g" "$INSTALL_DIR/$WRAPPER_NAME"

# Make executable
chmod +x "$INSTALL_DIR/$WRAPPER_NAME"

echo "✅ GitGovernance CLI installed successfully!"
echo ""
echo "🎯 Usage from ANY directory:"
echo "   gitgov init --name \"My Project\""
echo "   gitgov status"
echo "   gitgov dashboard"
echo ""
echo "📁 Works from:"
echo "   • Your development projects"
echo "   • /tmp/ for testing"
echo "   • Any directory with git init"
echo ""
echo "💡 For demos: cd /tmp && mkdir demo && cd demo && git init && gitgov init"
